services:
  gitlab:
    image: gitlab/gitlab-ce:$GITLAB_TAG
    container_name: gitlab
    restart: always
    hostname: $GITLAB_HOSTNAME
    environment:
      GITLAB_OMNIBUS_CONFIG: external_url 'http://$GITLAB_HOSTNAME';
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - "./volumes/gitlab/config:/etc/gitlab"
      - "./volumes/gitlab/logs:/var/log/gitlab"
      - "./volumes/gitlab/data:/var/opt/gitlab"
    shm_size: "256m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/-/health"]
      interval: 15s
      timeout: 10s
      retries: 12
  runner1:
    image: gitlab/gitlab-runner:$RUNNER_TAG
    container_name: runner1
    restart: always
    hostname: $RUNNER_HOSTNAME
    volumes:
      - "./volumes/runner:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./dockerfiles/runner/setup-ssh-prerequisite.sh:/usr/local/bin/copy-ssh-prerequisite.sh:ro"
      - "./dockerfiles/runner/init-runner.sh:/usr/local/bin/init-runner.sh:ro"
    entrypoint: ["/usr/local/bin/init-runner.sh"]
    environment:
      - TARGET_HOSTNAME=${WEBSERVER_HOSTNAME}
    depends_on:
      - web
  web:
    build:
      context: ./dockerfiles/webserver/
      dockerfile: Dockerfile
    container_name: web
    restart: always
    hostname: $WEBSERVER_HOSTNAME
    ports:
      - "3001:80"
    volumes:
      - "./volumes/web/www:/usr/local/apache2/htdocs"
