services:
  gitlab:
    image: gitlab/gitlab-ce:$GITLAB_TAG
    container_name: gitlab
    restart: always
    hostname: $GITLAB_HOSTNAME
    environment:
      GITLAB_OMNIBUS_CONFIG: external_url 'http://$GITLAB_HOSTNAME';
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - "./volumes/gitlab/config:/etc/gitlab"
      - "./volumes/gitlab/logs:/var/log/gitlab"
      - "./volumes/gitlab/data:/var/opt/gitlab"
    shm_size: "256m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/-/health"]
      interval: 15s
      timeout: 10s
      retries: 12
    networks:
      - gitlab_net
  runner1:
    image: gitlab/gitlab-runner:$RUNNER_TAG
    container_name: runner1
    restart: always
    hostname: $RUNNER_HOSTNAME
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./volumes/runner/config:/etc/gitlab-runner/"
    networks:
      - gitlab_net
  web:
    build:
      context: ./web/
    container_name: web
    restart: always
    hostname: $WEBSERVER_HOSTNAME
    ports:
      - "3001:80"
    volumes:
      - "./volumes/web/www:/usr/local/apache2/htdocs"
    networks:
      - webservers_net
  deployer:
    build:
      context: ./deployer/
    container_name: deployer
    restart: always
    hostname: $DEPLOYER_HOSTNAME
    ports:
      - "2222:22"
    volumes:
      - "./volumes/web/www:/home/gitlab-runner/www/"
      - "./volumes/deployer/gitlab-runner/ssh/:/home/gitlab-runner/.ssh/"
      - "./volumes/deployer/ssh/:/etc/ssh/"
    networks:
      - webservers_net
      - gitlab_net

networks:
  gitlab_net:
  webservers_net:
